pipeline {

    agent any

    environment {

        IMAGE_NAME = "voyageanalytics"

    }

    stages {

        stage('Install Dependencies') {

            steps {

                sh 'pip install -r requirements.txt'

            }

        }

        stage('Run Regression Model') {

            steps {

                sh 'python regression_model/train_regression.py'

            }

        }

        stage('Run Classification Model') {

            steps {

                sh 'python classification_model/train_classification.py'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t voyageanalytics .'

            }

        }

    }

}