pipeline {

    agent any

    stages {

        stage('Clone Repository') {

            steps {

                git 'https://github.com/akshat-mishra-ds/Voyage-Analytics-Integrating-MLOps-in-Travel'

            }

        }

        stage('Install Dependencies') {

            steps {

                bat 'pip install -r requirements.txt'

            }

        }

        stage('Run Tests') {

            steps {

                bat 'python regression_model/train_regression.py'

            }

        }

        stage('Build Docker Image') {

            steps {

                bat 'docker build -t voyageanalytics .'

            }

        }

    }

}